name: Self-Hosted Runner Test

on: [push]   # triggers workflow on every push

jobs:
  build:
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from my self-hosted runner!"
